name = "twopnt"
version = "0.1.0"
license = "license"
author = "Federico Perini"
maintainer = "federico.perini@gmail.com"
copyright = "Copyright 2023, Federico Perini"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = "twopnt"
[install]
library = false
[fortran]
implicit-typing = true
implicit-external = true
source-form = "default"

